/**
 * Utility tools (1 tool)
 * Helper tools for developer workflow
 */

import { z } from 'zod';
import type { ToolDefinition, ToolHandler } from '../types/tools.js';
import { textResponse, zitadelId } from '../types/tools.js';
import type { ZitadelApp } from '../types/zitadel.js';

// ─── Tool Definitions ───────────────────────────────────────────────────────

export const UTILITY_TOOLS: ToolDefinition[] = [
  {
    name: 'zitadel_get_auth_config',
    description: 'Get the environment variables needed for a new application\'s .env.local file. Fetches the app details and formats them as ready-to-paste configuration.',
    inputSchema: {
      type: 'object',
      properties: {
        projectId: { type: 'string', description: 'The project ID' },
        appId: { type: 'string', description: 'The application ID' },
      },
      required: ['projectId', 'appId'],
    },
    _meta: { readOnly: true, domain: 'utility' },
    annotations: { title: 'Get Auth Config', readOnlyHint: true, destructiveHint: false, idempotentHint: true },
  },
];

// ─── Handlers ────────────────────────────────────────────────────────────────

const getAuthConfigHandler: ToolHandler = async (params, ctx) => {
  const input = z.object({
    projectId: zitadelId('projectId'),
    appId: zitadelId('appId'),
  }).parse(params);

  const app = await ctx.client.request<ZitadelApp>(
    `/management/v1/projects/${input.projectId}/apps/${input.appId}`
  );

  const clientId = app.oidcConfig?.clientId || 'UNKNOWN';
  const config = ctx.client.getConfig();

  const envVars = [
    `# Zitadel OIDC Configuration for "${app.name}"`,
    `# Generated by zitadel-mcp-server`,
    ``,
    `AUTH_ZITADEL_ISSUER=${config.issuer}`,
    `AUTH_ZITADEL_CLIENT_ID=${clientId}`,
    ``,
    `# Additional context (for reference)`,
    `# ZITADEL_PROJECT_ID=${input.projectId}`,
    `# ZITADEL_ORG_ID=${config.orgId}`,
    `# ZITADEL_APP_ID=${input.appId}`,
  ];

  return textResponse(envVars.join('\n'));
};

// ─── Export ──────────────────────────────────────────────────────────────────

export const UTILITY_HANDLERS: Record<string, ToolHandler> = {
  zitadel_get_auth_config: getAuthConfigHandler,
};
